[package]
name = "libmarpa-sys"
version = "0.1.2"
authors = ["Josh Chase <jcjoshuachase@gmail.com>"]
build = "build.rs"
description = "Low-level bindings to the libmarpa parsing engine"
license = "MIT"
repository = "https://github.com/Pursuit92/libmarpa-sys"

[dependencies]
libc = "*"
